[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "no-cache"

[[redirects]]
  from = "https://www.jmirrigationco.com/*"
  to = "https://jmirrigationco.com/:splat"
  status = 301
  force = true
